version: '2'

services:
  carts:
    image: TAG_TO_REPLACE
    hostname: carts
    restart: always
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid
    environment:
      - reschedule=on-node-failure
      - ZIPKIN_ENABLED=false
      - DT_CUSTOM_PROP=app=carts environment=dev
      - JAVA_OPTS=-Xms64m -Xmx128m -XX:+UseG1GC
    ports:
      - "8082:80"
  carts-db:
    image: mongo:3.4
    hostname: carts-db
    restart: always
    cap_drop:
      - all
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    read_only: true
    environment:
      - DT_CUSTOM_PROP=app=carts-db environment=dev
    tmpfs:
      - /tmp:rw,noexec,nosuid
networks:
  default:
    external:
      name: TO_REPLACE